version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: "checking Versions"
          command: |
            node --version
      - run:
          name: "Frontend Install"
          command: |
            npm run frontend:install
      - run:
          name: "Backend Install"
          command: |
            npm run backend:install
      - run:
          name: "Frontend Build"
          command: |
            npm run frontend:build
      - run:
          name: "Backend Build"
          command: |
            npm run backend:build
      - run:
          name: "Frontend Test"
          command: |
            npm run frontend:test
      - run:
          name: "Backend Test"
          command: |
            npm run backend:test
      - run:
          name: "Deploy Backend EB"
          command: |
            npm run backend:deploy
      - run:
          name: "Deploy Frontend S3"
          command: |
            npm run frontend:deploy
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main