# Specify circleci version that pipeline should use.
version: 2.1
orbs:
  # Declaring the orbs that circleci server will use during Ci/Cd. (nodeJs, Aws-cli, EB).
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
# Defining the jobs
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      # setup and install all dependencies to run the install, build, test and deploy scripts.
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: "checking Versions"
          command: |
            node --version
      # install dependencies for frontend and backend
      - run:
          name: "Frontend Install"
          command: |
            npm run frontend:install
      - run:
          name: "Backend Install"
          command: |
            npm run backend:install
      # run build scripts for frontend and backend
      - run:
          name: "Frontend Build"
          command: |
            npm run frontend:build
      - run:
          name: "Backend Build"
          command: |
            npm run backend:build
      # run Test scripts for frontend and backend
      - run:
          name: "Frontend Test"
          command: |
            npm run frontend:test
      - run:
          name: "Backend Test"
          command: |
            npm run backend:test
      # finally run deploy scripts for frontend and backend to deploy to aws using aws-cli
      - run:
          name: "Deploy Backend EB"
          command: |
            npm run backend:deploy
      - run:
          name: "Deploy Frontend S3"
          command: |
            npm run frontend:deploy
# Orchestrate our job run sequence
# Specify how the jobs should be handled
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
          # Specify the branch which the pipeline will trigger. 
            branches:
              only: main